services:
  mqtt-ingestor:
    build: ./mqtt_ingestor
    container_name: mqtt-ingestor
    depends_on:
      - rabbitmq
    environment:
      - MQTT_BROKER_REMOTE=${MQTT_HOST}
      - MQTT_BROKER_PORT=${MQTT_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - EXCHANGE_NAME=${RABBITMQ_EXCHANGE}
      - QUEUE_NAME=${RABBITMQ_QUEUE}
    networks:
      - backend-network

  opcua-server:
    build: ./opcua_server
    container_name: opcua-server
    ports:
      - "4840:4840"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - EXCHANGE_NAME=${RABBITMQ_EXCHANGE}
      - QUEUE_NAME=${RABBITMQ_QUEUE}
      - NAMESPACE=${OPCUA_NAMESPACE}
    networks:
      - backend-network

  api-service:
    build: ./api_service
    container_name: api-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - backend-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - api-service
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge